name = "slippilab"
pages_build_output_dir = "build/client"
compatibility_date = "2024-04-03"

[[d1_databases]]
database_id = "034f632f-7256-47bb-b553-5c14944bf3d8"
binding = "DB"
database_name = "DB"

[[r2_buckets]]
bucket_name = "slippilab-migration"
binding = "BUCKET"

[env.production]
compatibility_date = "2024-04-03"

  [[env.production.d1_databases]]
  database_id = "034f632f-7256-47bb-b553-5c14944bf3d8"
  binding = "DB"
  database_name = "DB"

  [[env.production.r2_buckets]]
  bucket_name = "slippilab-migration"
  binding = "BUCKET"
